apiVersion: v1

kind: Pod

metadata:

 name: helloworld

 labels:

      app: 2048-ws
spec:
 containers:

  - name: helloworld
    image: omarhasni123/helloworld

    ports:

      - containerPort: 8000

        protocol: TCP

